<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="WebApplication1.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <center>    
            <h1>&nbsp;</h1>
                <h1>&nbsp;</h1>
                <h1>INSERT UPDATE DELETE</h1>
                <asp:GridView ID="GridView1" runat="server"    AutoGenerateColumns="false" AutoGenerateDeleteButton="true"
                    OnRowDeleting="GridView1_RowDeleting" AutoGenerateEditButton="true" OnRowEditing="GridView1_RowEditing"
                    OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowUpdating="GridView1_RowUpdating" 
                    OnRowCommand="GridView1_RowCommand">
                    <Columns>
                        <asp:TemplateField HeaderText="Employ Number ">
                            <ItemTemplate> 
                            <asp:Label runat="server" ID="lbml" Text='<%#Eval("EmpNo") %>'></asp:Label>
                                 </ItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="Footer1" runat="server"></asp:TextBox>
                            </FooterTemplate>
                        </asp:TemplateField>                
                        <asp:TemplateField HeaderText="Employe Name" >
                            <ItemTemplate>
                                <%#Eval("EmpName") %>
                            </ItemTemplate>
                             <FooterTemplate>
                                 <asp:TextBox ID="Footer2" runat="server"></asp:TextBox>
                             </FooterTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Employe Salary">
                            <ItemTemplate>
                                <%#Eval("EmpSal") %>
                            </ItemTemplate>
                             <EditItemTemplate>
         <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
                            </EditItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="Footer3" runat="server"></asp:TextBox>
                            </FooterTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Insert" >                   
                            <ItemTemplate>
                                <asp:LinkButton ID="LinkButton1" CommandName="add" Text="Add" runat="server"> 
                                </asp:LinkButton>
                            </ItemTemplate>
                            <FooterTemplate>                            
                                    <asp:Button ID="Button1" runat="server" CommandName="save" Text="Save" />
                            </FooterTemplate>
                        </asp:TemplateField>
                    </Columns>
          </asp:GridView>
                <br />
                <br />
                <br />
                <strong>
                <asp:Label ID="LBLMSG" runat="server" Font-Size="XX-Large"></asp:Label>
                </strong>
         </center>
        </div>
    </form>
</body>
</html>
